# Generated by Django 3.1.5 on 2021-01-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20210124_0354'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='discussion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='discussions.discussion'),
            preserve_default=False,
        ),
    ]
