# Generated by Django 3.1.5 on 2021-01-24 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('discussions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='body',
        ),
        migrations.AddField(
            model_name='discussion',
            name='categories',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
            preserve_default=False,
        ),
    ]
